server.port=9000

spring.application.name=nat-gateway


# Conectar al Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888

# Eureka (opcional, si el config-server ya lo tiene, puedes borrar esto)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/