spring.application.name=pagos-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888

# Timeout para que no se cuelgue al arrancar
spring.cloud.config.request-connect-timeout=2000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver