server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Si no le pasamos variable de entorno, usa localhost. Si estamos en Docker, usaremos la variable.
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}