server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Esto debe apuntar a la carpeta que mapeamos en el compose
          search-locations: file:/config-microservicios