server:
  address: 0.0.0.0
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Carrito
        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/api/v1/carrito/**, /v3/api-docs/carrito-service/**
          filters:
            - RewritePath=/v3/api-docs/carrito-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Cliente
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/v1/clientes/**, /v3/api-docs/cliente-service/**
          filters:
            - RewritePath=/v3/api-docs/cliente-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Envios
        - id: envios-service
          uri: lb://envios-service
          predicates:
            - Path=/api/v1/envios/**, /v3/api-docs/envios-service/**
          filters:
            - RewritePath=/v3/api-docs/envios-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Inventario
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/api/v1/inventario/**, /v3/api-docs/inventario-service/**
          filters:
            - RewritePath=/v3/api-docs/inventario-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Notificaciones
        - id: notificaciones-service
          uri: lb://notificaciones-service
          predicates:
            - Path=/api/v1/notificaciones/**, /v3/api-docs/notificaciones-service/**
          filters:
            - RewritePath=/v3/api-docs/notificaciones-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Pagos
        - id: pagos-service
          uri: lb://pagos-service
          predicates:
            - Path=/api/v1/pagos/**, /v3/api-docs/pagos-service/**
          filters:
            - RewritePath=/v3/api-docs/pagos-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Pedidos
        - id: pedidos-service
          uri: lb://pedidos-service
          predicates:
            - Path=/api/v1/pedidos/**, /v3/api-docs/pedidos-service/**
          filters:
            - RewritePath=/v3/api-docs/pedidos-service(?<segment>/?.*), /v3/api-docs$\{segment}

        # Productos
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/v1/productos/**, /v3/api-docs/producto-service/**
          filters:
            - RewritePath=/v3/api-docs/producto-service(?<segment>/?.*), /v3/api-docs$\{segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Carrito
        url: /v3/api-docs/carrito-service
      - name: Cliente
        url: /v3/api-docs/cliente-service
      - name: Envios
        url: /v3/api-docs/envios-service
      - name: Inventario
        url: /v3/api-docs/inventario-service
      - name: Notificaciones
        url: /v3/api-docs/notificaciones-service
      - name: Pagos
        url: /v3/api-docs/pagos-service
      - name: Pedidos
        url: /v3/api-docs/pedidos-service
      - name: Productos
        url: /v3/api-docs/producto-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true