spring.application.name=api-gateway

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
server.address=0.0.0.0

# --- Rutas de Gateway Corregidas ---

# 0. Cliente
spring.cloud.gateway.routes[0].id=cliente-service
spring.cloud.gateway.routes[0].uri=lb://cliente-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clientes/**

# 1. Carrito 
spring.cloud.gateway.routes[1].id=carrito-service
spring.cloud.gateway.routes[1].uri=lb://carrito-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/carrito/**

# 2. Inventario
spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=lb://inventario-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventario/**

# 3. Pagos
spring.cloud.gateway.routes[3].id=pagos-service
spring.cloud.gateway.routes[3].uri=lb://pagos-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pagos/**

# 4. Pedidos 
spring.cloud.gateway.routes[4].id=pedidos-service
spring.cloud.gateway.routes[4].uri=lb://pedidos-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pedidos/**

# 5. Envios 
spring.cloud.gateway.routes[5].id=envios-service
spring.cloud.gateway.routes[5].uri=lb://envios-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/envios/**

# 6. Producto
spring.cloud.gateway.routes[6].id=producto-service
spring.cloud.gateway.routes[6].uri=lb://producto-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/productos/**

# 7. Notificaciones
spring.cloud.gateway.routes[7].id=notificaciones-service
spring.cloud.gateway.routes[7].uri=lb://notificaciones-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notificaciones/**