server:
  port: 0
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  cloud:
    loadbalancer:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs