# 1. Borramos el server.port de aquí para que el local (9000) sea el que mande
# 2. Mantenemos el nombre de la app para que Eureka lo identifique (le puse nat-gateway pa' que calce con tu carpeta)
spring.application.name=nat-gateway

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# --- Rutas de Gateway (Ordenadas y mapeadas a tus carpetas) ---

# 0. Cliente (Reemplaza a usuario)
spring.cloud.gateway.server.webflux.routes[0].id=cliente-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://cliente-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/clientes/**

# 1. Carrito
spring.cloud.gateway.server.webflux.routes[1].id=carrito-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://carrito-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/carritos/**

# 2. Inventario
spring.cloud.gateway.server.webflux.routes[2].id=inventario-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/inventario/**

# 3. Pagos
spring.cloud.gateway.server.webflux.routes[3].id=pagos-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://pagos-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/pagos/**

# 4. Pedidos (Reemplaza a facturaciones)
spring.cloud.gateway.server.webflux.routes[4].id=pedidos-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://pedidos-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/pedidos/**

# 5. Envios (Reemplaza a transporte)
spring.cloud.gateway.server.webflux.routes[5].id=envios-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://envios-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/envios/**

# 6. Producto
spring.cloud.gateway.server.webflux.routes[6].id=producto-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://producto-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/productos/**

# 7. Notificaciones
spring.cloud.gateway.server.webflux.routes[7].id=notificaciones-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://notificaciones-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/notificaciones/**

server.address=0.0.0.0