spring:
  application:
    name: carrito-service
  config:
    import: "optional:configserver:http://config-server:8888" # El 'optional:' es clave
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false # Esto evita que se muera si no conecta al toque
      retry:
        enabled: true
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5